### ISSUE TITLE
Dead link: SmartSim (Chen2016) PDF link returns 404

### ISSUE THREAD

**Issue by levaphenyl** [klemenjak/nilm-papers-with-code#1]
In the __Synthetic Datasets and Generators__ section, the PDF link to Chen's SmartSim paper is dead. The current link points to https://github.com/klemenjak/nilm-papers-with-code/blob/master, while the actual link is http://www.ecs.umass.edu/~irwin/smartsim.pdf.

**Comment by klemenjak** [comment]
Hi! Thanks for pointing out this issue. I fixed it :)
