### ISSUE TITLE
Link to REDD dataset does not work

### ISSUE THREAD

**Issue by sriharshAmur** [klemenjak/nilm-papers-with-code#4]
Hi, The link to the [ REDD dataset](http://redd.csail.mit.edu/) does not load anymore. Is there an alternate link that provides access to the dataset?

**Comment by foreverxq** [comment]
确实。

**Comment by klemenjak** [comment]
https://web.archive.org/web/20220812015008/http://redd.csail.mit.edu/ seems to be the fix
